### PR TITLE
Update to v0.7

### PR DESCRIPTION
**Pull request by MasonProtter**
I've updated the package to work on Julia 0.7

### CODE REVIEW

**Comment by MasonProtter** [comment]
Other than changing `@def` to `@contract` I think everything I've done has been a pretty conservative update to the new syntax. If you don't like `@contract` it can be changed back.

**Comment by eschnett** [comment]
@MasonProtter Thanks for you pull request. There seems to be a syntax error in `appveyor.yml` – are you looking into this?

**Comment by MasonProtter** [comment]
Yes, I just don’t know what I’m doing. I also don’t know why it’s not running through Travis anymore

**Comment by MasonProtter** [comment]
Okay, so Appveyor is happy. Do you have any ideas as to why it appears to not want to run Travis?

**Comment by MasonProtter** [comment]
@eschnett Okay, so Appveyor is happy. Do you have any ideas as to why it appears to not want to run Travis?

**Comment by eschnett** [comment]
Is this now ready to be merged?

**Comment by MasonProtter** [comment]
For some reason, Travis isn’t running the tests and I can’t figure out why. Is Travis enabled on this repo?

**Comment by MasonProtter** [comment]
Hey @eschnett, so I ran the tests locally on my machine again and everything seems to work. I still don't know why Travis isn't running but appveyor at least is happy. Can we merge this?

**Pull request merged**
